/* ─── DOCS DATA ─── */
const DOCS = {
  quickstart: {
    label: 'Quick Start',
    breadcrumb: 'Getting Started / Quick Start',
    html: `
<h2>Quick Start</h2>
<p>Scaffold and run your first EFC API in under a minute.</p>
<h3>1. Create a new project</h3>
<pre><span class="c-dim">$</span> <span class="c-green">npx</span> create-efc-app my-api</pre>
<p>The interactive scaffolder will ask you to choose:</p>
<ul>
  <li><strong>Language</strong> — TypeScript or JavaScript</li>
  <li><strong>Database</strong> — MongoDB or PostgreSQL</li>
  <li><strong>Auth strategy</strong> — <code>http-only</code> or <code>localStorage</code></li>
  <li><strong>Clustering</strong> — enable (recommended for production)</li>
  <li><strong>Background tasks</strong> — BullMQ (Redis) or pg-boss</li>
</ul>
<h3>2. Start the dev server</h3>
<pre><span class="c-dim">$</span> cd my-api
<span class="c-dim">$</span> efc start dev

<span class="c-green">✔ Worker 1 ready on :3000
→ GET  /health       src/api/health.ts
→ GET  /users        src/api/users/index.ts</span></pre>
<h3>3. Add a route</h3>
<pre><span class="c-dim"># scaffold a new route file</span>
<span class="c-dim">$</span> efc generate route posts/[slug]
<span class="c-green">→ Created src/api/posts/[slug].ts</span></pre>
<p>That's it — the file is automatically registered as <code>GET /posts/:slug</code>.</p>
`,
  },
  structure: {
    label: 'Project Structure',
    breadcrumb: 'Getting Started / Project Structure',
    html: `
<h2>Project Structure</h2>
<p>Every EFC project follows a consistent layout generated by <code>create-efc-app</code>.</p>
<pre>my-api/
├── src/
│   ├── api/                 <span class="c-dim"># routes</span>
│   │   ├── health.ts        <span class="c-dim"># GET /health</span>
│   │   └── users/
│   │       ├── index.ts     <span class="c-dim"># GET /users · POST /users</span>
│   │       └── [id].ts      <span class="c-dim"># GET /users/:id · DELETE /users/:id</span>
│   ├── tasks/               <span class="c-dim"># background jobs</span>
│   │   └── SendEmail.ts
│   ├── models/              <span class="c-dim"># engine-agnostic models</span>
│   │   └── User.ts
│   └── index.ts             <span class="c-dim"># ignite() entry point</span>
├── efc.config.ts
├── .env                     <span class="c-dim"># gitignored — JWT_SECRET auto-filled</span>
├── .env.example
└── package.json</pre>
<h3>Key Conventions</h3>
<ul>
  <li>Every file in <code>src/api/</code> becomes a route</li>
  <li><code>[brackets]</code> in filenames become dynamic params (<code>:id</code>)</li>
  <li><code>index.ts</code> maps to the directory path</li>
  <li>Every file in <code>src/tasks/</code> registers a named background task</li>
</ul>
`,
  },
  config: {
    label: 'Configuration',
    breadcrumb: 'Getting Started / Configuration',
    html: `
<h2>Configuration</h2>
<p>EFC uses a <code>efc.config.ts</code> file at the root. It's auto-generated by <code>create-efc-app</code> and fully overridable.</p>
<pre><span class="c-purple">import type</span> { EFCConfig } <span class="c-purple">from</span> <span class="c-green">'express-file-cluster'</span>;

<span class="c-purple">const</span> config: EFCConfig = {
  port: Number(process.env.PORT) || <span class="c-orange">3000</span>,
  basePath:  <span class="c-green">'/api'</span>,
  dashboard: process.env.NODE_ENV !== <span class="c-green">'production'</span>,
  database:    <span class="c-green">'mongodb'</span>,
  databaseUrl: process.env.DATABASE_URL!,
  authStrategy: <span class="c-green">'http-only'</span>,
  jwtSecret:   process.env.JWT_SECRET!,
  cluster: process.env.NODE_ENV === <span class="c-green">'production'</span>,
  tasks: { backend: <span class="c-green">'bullmq'</span>, redisUrl: process.env.REDIS_URL, concurrency: <span class="c-orange">5</span> },
  globalMiddlewares: [],
};

<span class="c-purple">export default</span> config;</pre>
`,
  },
  routing: {
    label: 'File-Based Routing',
    breadcrumb: 'Core / File-Based Routing',
    html: `
<h2>File-Based Routing</h2>
<p>EFC scans <code>src/api/</code> at startup and builds the route map from the file tree. No registration required — add a file, get a route.</p>
<h3>Routing Rules</h3>
<table class="docs-table">
  <thead><tr><th>File</th><th>URL</th></tr></thead>
  <tbody>
    <tr><td>src/api/health.ts</td><td>/health</td></tr>
    <tr><td>src/api/users/index.ts</td><td>/users</td></tr>
    <tr><td>src/api/users/[id].ts</td><td>/users/:id</td></tr>
    <tr><td>src/api/posts/[slug]/comments.ts</td><td>/posts/:slug/comments</td></tr>
  </tbody>
</table>
<h3>Method Dispatching</h3>
<p>Export uppercase HTTP method names. Unimplemented methods return <strong>405 Method Not Allowed</strong> automatically.</p>
<pre><span class="c-purple">export const</span> <span class="c-blue">GET</span>    = <span class="c-purple">async</span> (req, res) => { <span class="c-dim">/* ... */</span> };
<span class="c-purple">export const</span> <span class="c-blue">POST</span>   = <span class="c-purple">async</span> (req, res) => { <span class="c-dim">/* ... */</span> };
<span class="c-purple">export const</span> <span class="c-blue">PUT</span>    = <span class="c-purple">async</span> (req, res) => { <span class="c-dim">/* ... */</span> };
<span class="c-purple">export const</span> <span class="c-blue">PATCH</span>  = <span class="c-purple">async</span> (req, res) => { <span class="c-dim">/* ... */</span> };
<span class="c-purple">export const</span> <span class="c-blue">DELETE</span> = <span class="c-purple">async</span> (req, res) => { <span class="c-dim">/* ... */</span> };</pre>
<h3>Route metadata (<code>meta</code> export)</h3>
<p>Export a <code>meta</code> object to document the route in the development dashboard. All fields are optional.</p>
<pre><span class="c-purple">export const</span> meta = {
  description: <span class="c-green">'Fetch a user by ID.'</span>,
  request: {
    params: { id: <span class="c-green">'usr_01HXZ'</span> },
    query:  { include: <span class="c-green">'profile'</span> },
  },
  response: {
    status: <span class="c-orange">200</span>,
    body: { id: <span class="c-green">'usr_01HXZ'</span>, name: <span class="c-green">'Ada Lovelace'</span>, createdAt: <span class="c-green">'2026-01-01T00:00:00.000Z'</span> },
  },
};</pre>
<p>The dashboard renders <code>response.body</code> values as their type names — <code>String</code>, <code>Number</code>, <code>Boolean</code>, <code>Date</code>. ISO date strings are detected automatically and shown as <code>Date</code>.</p>
`,
  },
  handlers: {
    label: 'Route Handlers',
    breadcrumb: 'Core / Route Handlers',
    html: `
<h2>Route Handlers</h2>
<p>Handlers are standard Express <code>async (req, res) =&gt; {}</code> functions — no new patterns to learn.</p>
<h3>Static Route</h3>
<pre><span class="c-dim">// src/api/health.ts → GET /health</span>
<span class="c-purple">export const</span> <span class="c-blue">GET</span> = <span class="c-purple">async</span> (req, res) => {
  res.<span class="c-blue">json</span>({ status: <span class="c-green">'OK'</span>, ts: <span class="c-purple">new</span> Date().<span class="c-blue">toISOString</span>() });
};</pre>
<h3>Dynamic Route</h3>
<pre><span class="c-dim">// src/api/users/[id].ts → GET /users/:id</span>
<span class="c-purple">import</span> { HttpError } <span class="c-purple">from</span> <span class="c-green">'express-file-cluster'</span>;

<span class="c-purple">export const</span> <span class="c-blue">GET</span> = <span class="c-purple">async</span> (req, res) => {
  <span class="c-purple">const</span> user = <span class="c-purple">await</span> User.<span class="c-blue">findById</span>(req.params.id);
  <span class="c-purple">if</span> (!user) <span class="c-purple">throw new</span> <span class="c-blue">HttpError</span>(<span class="c-orange">404</span>, <span class="c-green">'User not found'</span>);
  res.<span class="c-blue">json</span>(user);
};</pre>
`,
  },
  middleware: {
    label: 'Middleware',
    breadcrumb: 'Core / Middleware',
    html: `
<h2>Middleware</h2>
<p>EFC supports three tiers of middleware with clear scopes.</p>
<h3>1. Global Middleware</h3>
<pre><span class="c-blue">ignite</span>({ globalMiddlewares: [cors(), rateLimiter] });</pre>
<h3>2. Route-Level Middleware</h3>
<pre><span class="c-dim">// Applied to all handlers in this file</span>
<span class="c-purple">export const</span> middlewares = [requireAuth, authorize(<span class="c-green">'admin'</span>)];

<span class="c-purple">export const</span> <span class="c-blue">DELETE</span> = <span class="c-purple">async</span> (req, res) => { <span class="c-dim">/* ... */</span> };</pre>
<h3>3. Handler-Level via <code>compose()</code></h3>
<pre><span class="c-purple">import</span> { compose } <span class="c-purple">from</span> <span class="c-green">'express-file-cluster'</span>;

<span class="c-purple">export const</span> <span class="c-blue">POST</span> = <span class="c-blue">compose</span>(
  <span class="c-blue">validateBody</span>(CreateUserSchema),
  <span class="c-purple">async</span> (req, res) => {
    <span class="c-dim">// req.body is validated here</span>
  }
);</pre>
`,
  },
  errors: {
    label: 'Error Handling',
    breadcrumb: 'Core / Error Handling',
    html: `
<h2>Error Handling</h2>
<p>Throw from any handler — EFC catches it and sends a clean JSON response.</p>
<h3>HttpError</h3>
<pre><span class="c-purple">import</span> { HttpError } <span class="c-purple">from</span> <span class="c-green">'express-file-cluster'</span>;

<span class="c-purple">export const</span> <span class="c-blue">GET</span> = <span class="c-purple">async</span> (req, res) => {
  <span class="c-purple">const</span> user = <span class="c-purple">await</span> User.<span class="c-blue">findById</span>(req.params.id);
  <span class="c-purple">if</span> (!user) <span class="c-purple">throw new</span> <span class="c-blue">HttpError</span>(<span class="c-orange">404</span>, <span class="c-green">'User not found'</span>);
  res.<span class="c-blue">json</span>(user);
};</pre>
<h3>Custom Global Handler</h3>
<pre><span class="c-blue">ignite</span>({
  <span class="c-blue">onError</span>: (err, req, res, next) => {
    logger.<span class="c-blue">error</span>(err);
    res.<span class="c-blue">status</span>(err.statusCode ?? <span class="c-orange">500</span>).<span class="c-blue">json</span>({ error: err.message });
  },
});</pre>
`,
  },
  clustering: {
    label: 'Clustering',
    breadcrumb: 'Features / Clustering',
    html: `
<h2>Clustering</h2>
<p>With <code>cluster: true</code>, EFC forks <code>os.cpus().length</code> workers. All share the same port — the OS round-robins connections across them.</p>
<h3>Pre-Flight Lifecycle (per worker)</h3>
<ul>
  <li>Connect database — establish this worker's pool</li>
  <li>Configure auth — wire JWT keys and cookie options</li>
  <li>Register tasks — scan <code>src/tasks/</code> and attach queue consumers</li>
  <li>Scan <code>src/api/</code> — build route map from the filesystem</li>
  <li>Mount routes — register handlers on Express</li>
  <li>Start listening — announce readiness</li>
</ul>
<h3>Self-Healing</h3>
<p>If a worker crashes, the master fires <code>onWorkerCrash</code>, immediately forks a replacement, and runs the full Pre-Flight lifecycle before serving traffic.</p>
<pre><span class="c-blue">ignite</span>({
  cluster: <span class="c-orange">true</span>,
  workers: <span class="c-orange">4</span>, <span class="c-dim">// default: os.cpus().length</span>
  <span class="c-blue">onWorkerReady</span>: (id) => console.<span class="c-blue">log</span>(<span class="c-green">\`Worker \${id} ready\`</span>),
  <span class="c-blue">onWorkerCrash</span>: (id, code) => console.<span class="c-blue">error</span>(<span class="c-green">\`Worker \${id} crashed (\${code})\`</span>),
});</pre>
`,
  },
  tasks: {
    label: 'Background Tasks',
    breadcrumb: 'Features / Background Tasks',
    html: `
<h2>Background Tasks</h2>
<p>Define tasks in <code>src/tasks/</code>. Enqueue from any route handler. Respond immediately — the job runs later.</p>
<h3>Defining an I/O-bound task</h3>
<pre><span class="c-purple">import</span> { defineTask } <span class="c-purple">from</span> <span class="c-green">'express-file-cluster/tasks'</span>;

<span class="c-purple">export default</span> <span class="c-blue">defineTask</span>&lt;{ to: string; subject: string }&gt;(
  <span class="c-purple">async</span> (payload) => { <span class="c-purple">await</span> mailer.<span class="c-blue">send</span>(payload); }
);</pre>
<h3>CPU-bound task (worker_threads)</h3>
<pre><span class="c-purple">export default</span> <span class="c-blue">defineTask</span>&lt;{ key: string; width: number }&gt;(
  { thread: <span class="c-orange">true</span> },
  <span class="c-purple">async</span> ({ key, width }) => {
    <span class="c-purple">const</span> out = <span class="c-purple">await</span> sharp(<span class="c-purple">await</span> <span class="c-blue">download</span>(key)).<span class="c-blue">resize</span>(width).<span class="c-blue">toBuffer</span>();
    <span class="c-purple">await</span> <span class="c-blue">upload</span>(\`\${key}@\${width}\`, out);
  }
);</pre>
<h3>Task Options</h3>
<table class="docs-table">
  <thead><tr><th>Option</th><th>Default</th><th>Description</th></tr></thead>
  <tbody>
    <tr><td>thread</td><td>false</td><td>Run in worker_threads</td></tr>
    <tr><td>retries</td><td>3</td><td>Retry attempts before dead-letter</td></tr>
    <tr><td>backoff</td><td>'exponential'</td><td>Delay strategy between retries</td></tr>
    <tr><td>concurrency</td><td>tasks.concurrency</td><td>Parallel jobs for this task</td></tr>
    <tr><td>schedule</td><td>—</td><td>Cron expression for recurring tasks</td></tr>
  </tbody>
</table>
`,
  },
  auth: {
    label: 'Authentication',
    breadcrumb: 'Features / Authentication',
    html: `
<h2>Authentication</h2>
<p>Choose your strategy during scaffolding. Both ship JWT-based token management.</p>
<h3>http-only (recommended for SSR)</h3>
<p>Tokens stored in <strong>HttpOnly + Secure + SameSite=Strict</strong> cookies.</p>
<pre><span class="c-purple">import</span> { issueToken, revokeToken, requireAuth }
  <span class="c-purple">from</span> <span class="c-green">'express-file-cluster/auth'</span>;

<span class="c-dim">// Login route</span>
<span class="c-purple">export const</span> <span class="c-blue">POST</span> = <span class="c-purple">async</span> (req, res) => {
  <span class="c-purple">const</span> user = <span class="c-purple">await</span> <span class="c-blue">verifyCredentials</span>(req.body);
  <span class="c-purple">await</span> <span class="c-blue">issueToken</span>(res, { sub: user.id, role: user.role });
  res.<span class="c-blue">json</span>({ message: <span class="c-green">'Logged in'</span> });
};

<span class="c-dim">// Protect a route</span>
<span class="c-purple">export const</span> middlewares = [requireAuth];</pre>
<h3>localStorage (SPA-friendly)</h3>
<pre><span class="c-purple">import</span> { signToken } <span class="c-purple">from</span> <span class="c-green">'express-file-cluster/auth'</span>;

<span class="c-purple">export const</span> <span class="c-blue">POST</span> = <span class="c-purple">async</span> (req, res) => {
  <span class="c-purple">const</span> token = <span class="c-purple">await</span> <span class="c-blue">signToken</span>({ sub: user.id });
  res.<span class="c-blue">json</span>({ token }); <span class="c-dim">// client: Authorization: Bearer &lt;token&gt;</span>
};</pre>
`,
  },
  database: {
    label: 'Database',
    breadcrumb: 'Features / Database',
    html: `
<h2>Database</h2>
<p>One unified model surface that compiles to Mongoose or Drizzle depending on your config.</p>
<h3>defineModel — engine-agnostic CRUD</h3>
<pre><span class="c-purple">import</span> { defineModel } <span class="c-purple">from</span> <span class="c-green">'express-file-cluster'</span>;

<span class="c-purple">export const</span> User = <span class="c-blue">defineModel</span>(<span class="c-green">'User'</span>, {
  name:  { type: <span class="c-green">'string'</span>, required: <span class="c-orange">true</span> },
  email: { type: <span class="c-green">'string'</span>, required: <span class="c-orange">true</span>, unique: <span class="c-orange">true</span> },
  role:  { type: <span class="c-green">'string'</span>, default: <span class="c-green">'member'</span> },
});</pre>
<h3>Available Methods</h3>
<table class="docs-table">
  <thead><tr><th>Method</th><th>Returns</th></tr></thead>
  <tbody>
    <tr><td>Model.find(filter?)</td><td>Record[]</td></tr>
    <tr><td>Model.findById(id)</td><td>Record | null</td></tr>
    <tr><td>Model.findOne(filter)</td><td>Record | null</td></tr>
    <tr><td>Model.create(data)</td><td>Record</td></tr>
    <tr><td>Model.update(id, data)</td><td>Record | null</td></tr>
    <tr><td>Model.delete(id)</td><td>void</td></tr>
    <tr><td>Model.count(filter?)</td><td>number</td></tr>
  </tbody>
</table>
<h3>Raw Client (escape hatch)</h3>
<pre><span class="c-purple">import</span> { db } <span class="c-purple">from</span> <span class="c-green">'express-file-cluster'</span>;
<span class="c-dim">// MongoDB: db is a mongoose.Connection</span>
<span class="c-dim">// PostgreSQL: db is a pg.Pool</span>
<span class="c-purple">const</span> { rows } = <span class="c-purple">await</span> db.<span class="c-blue">query</span>(<span class="c-green">'SELECT * FROM users WHERE id = $1'</span>, [id]);</pre>
`,
  },
  dashboard: {
    label: 'API Dashboard',
    breadcrumb: 'Features / API Dashboard',
    html: `
<h2>API Dashboard</h2>
<p>When <code>dashboard: true</code> is set and <code>NODE_ENV</code> is <code>development</code>, EFC mounts a live API documentation page at the root of your <code>basePath</code>. It lists every registered route with its method, path, description, and request/response examples — no external tooling required.</p>
<h3>Enabling it</h3>
<pre><span class="c-blue">ignite</span>({
  dashboard: <span class="c-orange">true</span>,
  basePath:  <span class="c-green">'/api'</span>, <span class="c-dim">// dashboard mounts at GET /api/</span>
});</pre>
<p>The page is <strong>only served when <code>NODE_ENV === 'development'</code></strong>. In production, the route does not exist.</p>
<h3>Documenting routes with <code>meta</code></h3>
<p>Export a <code>meta</code> object from any route file to populate the dashboard card for that route.</p>
<pre><span class="c-dim">// src/api/users/[id].ts</span>
<span class="c-purple">export const</span> meta = {
  description: <span class="c-green">'Fetch a user by ID.'</span>,
  request: {
    headers: { Authorization: <span class="c-green">'Bearer &lt;token&gt;'</span> },
    params:  { id: <span class="c-green">'usr_01HXZ'</span> },
    query:   { include: <span class="c-green">'profile'</span> },
  },
  response: {
    status: <span class="c-orange">200</span>,
    body: {
      id:        <span class="c-green">'usr_01HXZ'</span>,
      name:      <span class="c-green">'Ada Lovelace'</span>,
      createdAt: <span class="c-green">'2026-01-01T00:00:00.000Z'</span>,
    },
  },
};</pre>
<h3>Type rendering</h3>
<p>The dashboard renders <code>response.body</code> values as their <strong>type names</strong>, not the literal values you provide. This keeps examples readable without leaking real data.</p>
<table class="docs-table">
  <thead><tr><th>Value in meta</th><th>Shown in dashboard</th></tr></thead>
  <tbody>
    <tr><td>'Ada Lovelace'</td><td>String</td></tr>
    <tr><td>42891</td><td>Number</td></tr>
    <tr><td>true / false</td><td>Boolean</td></tr>
    <tr><td>'2026-01-01T00:00:00.000Z'</td><td>Date</td></tr>
  </tbody>
</table>
<p>ISO 8601 date strings are detected automatically — no annotation needed.</p>
<h3>RouteMeta interface</h3>
<pre><span class="c-purple">interface</span> <span class="c-blue">RouteMeta</span> {
  description?: string;
  request?: {
    headers?: Record&lt;string, string&gt;;
    params?:  Record&lt;string, string&gt;;
    query?:   Record&lt;string, string&gt;;
    body?:    unknown;
  };
  response?: {
    status?: number;
    body?:   unknown;
  };
}</pre>
`,
  },
  cli: {
    label: 'CLI Reference',
    breadcrumb: 'Reference / CLI',
    html: `
<h2>CLI Reference</h2>
<h3>Lifecycle</h3>
<table class="docs-table">
  <thead><tr><th>Command</th><th>Description</th></tr></thead>
  <tbody>
    <tr><td>efc start dev</td><td>Dev server — hot-reload, single process. <code>NODE_ENV</code> defaults to <code>development</code>; overridden by <code>.env</code> or parent environment</td></tr>
    <tr><td>efc build prod</td><td>Type-check + compile to dist/ (tsup, dual CJS/ESM)</td></tr>
    <tr><td>efc start prod</td><td>Run dist/ with clustering enabled</td></tr>
    <tr><td>efc run tests</td><td>Vitest — pass --watch or --coverage</td></tr>
  </tbody>
</table>
<h3>Code Generation</h3>
<table class="docs-table">
  <thead><tr><th>Command</th><th>Description</th></tr></thead>
  <tbody>
    <tr><td>efc generate route users/[id]</td><td>Scaffold a route module with method stubs</td></tr>
    <tr><td>efc generate task SendEmail</td><td>Scaffold a background task</td></tr>
    <tr><td>efc generate middleware authorize</td><td>Scaffold a middleware file</td></tr>
  </tbody>
</table>
<h3>Diagnostics</h3>
<table class="docs-table">
  <thead><tr><th>Command</th><th>Description</th></tr></thead>
  <tbody>
    <tr><td>efc routes</td><td>Print resolved route table (path → file → methods)</td></tr>
    <tr><td>efc tasks</td><td>List registered background tasks</td></tr>
    <tr><td>efc doctor</td><td>Validate config, env vars, DB connectivity</td></tr>
  </tbody>
</table>
`,
  },
  envvars: {
    label: 'Environment Variables',
    breadcrumb: 'Reference / Environment Variables',
    html: `
<h2>Environment Variables</h2>
<p><code>create-efc-app</code> generates a <code>.env</code> (gitignored, JWT_SECRET pre-filled) and <code>.env.example</code> (committed, documented placeholders).</p>
<table class="docs-table">
  <thead><tr><th>Variable</th><th>Required</th><th>Description</th></tr></thead>
  <tbody>
    <tr><td>PORT</td><td>No (3000)</td><td>HTTP listen port</td></tr>
    <tr><td>NODE_ENV</td><td>No</td><td>development | production | test</td></tr>
    <tr><td>DATABASE_URL</td><td>Yes</td><td>MongoDB or PostgreSQL connection string</td></tr>
    <tr><td>JWT_SECRET</td><td>Yes</td><td>JWT signing key — auto-generated by scaffolder</td></tr>
    <tr><td>JWT_EXPIRES_IN</td><td>No (7d)</td><td>Token lifetime: 15m, 1h, 7d …</td></tr>
    <tr><td>COOKIE_DOMAIN</td><td>No</td><td>Cookie domain for http-only auth</td></tr>
    <tr><td>REDIS_URL</td><td>If BullMQ</td><td>Redis connection for task queue</td></tr>
  </tbody>
</table>
`,
  },
};

/* ─── DOCS RENDERING ─── */
function renderAllDocs() {
  const contentEl = document.getElementById('docsContent');
  contentEl.innerHTML = '';
  
  for (const [key, doc] of Object.entries(DOCS)) {
    const wrappedHtml = doc.html.replace(/<table/g, '<div class="table-responsive"><table').replace(/<\/table>/g, '</table></div>');
    const sectionHtml = `
      <div id="doc-${key}" class="doc-section">
        ${wrappedHtml}
      </div>
    `;
    contentEl.insertAdjacentHTML('beforeend', sectionHtml);
  }
}

renderAllDocs();

/* ─── DOCS SCROLLSPY & NAVIGATION ─── */
const docsObserver = new IntersectionObserver((entries) => {
  entries.forEach((entry) => {
    if (entry.isIntersecting) {
      const key = entry.target.id.replace('doc-', '');
      document.querySelectorAll('.docs-nav-link').forEach((l) => {
        l.classList.toggle('active', l.dataset.doc === key);
      });
    }
  });
}, { rootMargin: '-100px 0px -60% 0px' });

document.querySelectorAll('.doc-section').forEach((sec) => docsObserver.observe(sec));

document.querySelectorAll('.docs-nav-link').forEach((link) => {
  link.addEventListener('click', (e) => {
    e.preventDefault();
    const key = link.dataset.doc;
    const target = document.getElementById('doc-' + key);
    if (target) {
      target.scrollIntoView({ behavior: 'smooth' });
    }
  });
});

/* ─── TABS ─── */
document.querySelectorAll('.tab').forEach((tab) => {
  tab.addEventListener('click', () => {
    document.querySelectorAll('.tab').forEach((t) => t.classList.remove('active'));
    document.querySelectorAll('.tab-pane').forEach((p) => p.classList.remove('active'));
    tab.classList.add('active');
    document.getElementById('tab-' + tab.dataset.tab).classList.add('active');
  });
});

/* ─── NAVBAR SCROLL ─── */
window.addEventListener('scroll', () => {
  document.getElementById('navbar').classList.toggle('scrolled', window.scrollY > 20);
});

/* ─── HAMBURGER ─── */
document.getElementById('hamburger').addEventListener('click', () => {
  document.getElementById('mobileMenu').classList.toggle('open');
});

/* ─── INTERSECTION OBSERVER — fade in on scroll ─── */
const observer = new IntersectionObserver(
  (entries) => {
    entries.forEach((entry) => {
      if (entry.isIntersecting) {
        entry.target.style.opacity = '1';
        entry.target.style.transform = 'translateY(0)';
      }
    });
  },
  { threshold: 0.1 },
);

document.querySelectorAll('.feature-card, .roadmap-phase, .cta-inner').forEach((el) => {
  el.style.opacity = '0';
  el.style.transform = 'translateY(20px)';
  el.style.transition = 'opacity .5s ease, transform .5s ease';
  observer.observe(el);
});
