/* ─── DOCS DATA ─── */
const DOCS = {
  quickstart: {
    label: 'Quick Start',
    breadcrumb: 'Getting Started / Quick Start',
    html: `
<h2>Quick Start</h2>
<p>Scaffold and run your first EFC API in under a minute.</p>
<h3>1. Create a new project</h3>
<pre><span class="c-dim">$</span> <span class="c-green">npx</span> create-efc-app my-api</pre>
<p>The interactive scaffolder will ask you to choose:</p>
<ul>
  <li><strong>Language</strong> — TypeScript or JavaScript</li>
  <li><strong>Database</strong> — MongoDB (works today) or PostgreSQL (scaffolds stubs only — adapter not yet implemented)</li>
  <li><strong>Auth strategy</strong> — <code>http-only</code> or <code>localStorage</code></li>
  <li><strong>Features</strong> (toggle any combination) — Multi-core clustering, Background tasks, API route documentation, User portal, Admin portal, RBAC, Mailer</li>
  <li><strong>Background tasks</strong> → queue backend — BullMQ (Redis, works today) or pg-boss (not yet implemented)</li>
  <li><strong>Mailer</strong> → email provider — Gmail (preconfigured, app-password prompt) or a custom SMTP host/port</li>
</ul>
<p>See <a href="#" onclick="document.querySelector('[data-doc=portals]').click()">Generated Portals</a>, <a href="#" onclick="document.querySelector('[data-doc=rbac]').click()">RBAC</a>, and <a href="#" onclick="document.querySelector('[data-doc=mailer]').click()">Mailer</a> for what each option actually generates.</p>
<h3>2. Start the dev server</h3>
<pre><span class="c-dim">$</span> cd my-api
<span class="c-dim">$</span> efc start dev

<span class="c-green">✔ Worker 1 ready on :3000
→ GET  /health       src/api/health.ts
→ GET  /users        src/api/users/index.ts</span></pre>
<h3>3. Add a route</h3>
<pre><span class="c-dim"># scaffold a new route file</span>
<span class="c-dim">$</span> efc generate route posts/[slug]
<span class="c-green">→ Created src/api/posts/[slug].ts</span></pre>
<p>That's it — the file is automatically registered as <code>GET /posts/:slug</code>.</p>
`,
  },
  structure: {
    label: 'Project Structure',
    breadcrumb: 'Getting Started / Project Structure',
    html: `
<h2>Project Structure</h2>
<p>Every EFC project follows a consistent layout generated by <code>create-efc-app</code>.</p>
<pre>my-api/
├── src/
│   ├── api/                 <span class="c-dim"># routes</span>
│   │   ├── health.ts        <span class="c-dim"># GET /health</span>
│   │   └── users/
│   │       ├── index.ts     <span class="c-dim"># GET /users · POST /users</span>
│   │       └── [id].ts      <span class="c-dim"># GET /users/:id · DELETE /users/:id</span>
│   ├── tasks/               <span class="c-dim"># background jobs (scanned non-recursively)</span>
│   │   └── SendEmail.ts
│   ├── model/               <span class="c-dim"># engine-agnostic models</span>
│   │   ├── User.ts
│   │   └── Role.ts          <span class="c-dim"># scaffolded by the RBAC option</span>
│   └── index.ts             <span class="c-dim"># ignite() entry point</span>
├── efc.config.ts
├── .env                     <span class="c-dim"># gitignored — JWT_SECRET (+ SMTP_* if Mailer enabled) auto-filled</span>
├── .env.example
└── package.json</pre>
<h3>Key Conventions</h3>
<ul>
  <li>Every file in <code>src/api/</code> becomes a route</li>
  <li><code>[brackets]</code> in filenames become dynamic params (<code>:id</code>)</li>
  <li><code>index.ts</code> maps to the directory path</li>
  <li>Every file in <code>src/tasks/</code> registers a named background task</li>
  <li><code>src/api/</code> and <code>src/tasks/</code> are fixed conventions — there's no <code>apiDir</code>/<code>tasksDir</code> config option</li>
</ul>
<p>Enabling <strong>User portal</strong> / <strong>Admin portal</strong> fills <code>src/model/</code> and <code>src/api/</code> out considerably — see <a href="#" onclick="document.querySelector('[data-doc=portals]').click()">Generated Portals</a>.</p>
`,
  },
  config: {
    label: 'Configuration',
    breadcrumb: 'Getting Started / Configuration',
    html: `
<h2>Configuration</h2>
<p>EFC uses a <code>efc.config.ts</code> file at the root for <strong>structural config</strong>. Runtime values — port, database URL, secrets, CORS origins — are read from <code>.env</code> automatically.</p>
<pre><span class="c-purple">import type</span> { EFCConfig } <span class="c-purple">from</span> <span class="c-green">'express-file-cluster'</span>;

<span class="c-dim">// Structural config only — PORT, DATABASE_URL, JWT_SECRET, CORS_ORIGINS come from .env</span>
<span class="c-purple">const</span> config: EFCConfig = {
  authStrategy: <span class="c-green">'http-only'</span>,
  tasks: { backend: <span class="c-green">'bullmq'</span>, concurrency: <span class="c-orange">5</span> },
  globalMiddlewares: [],
};

<span class="c-purple">export default</span> config;</pre>
<p>Clustering and task backend selection are passed directly to <code>ignite()</code> in <code>src/index.ts</code>:</p>
<pre><span class="c-purple">import</span> { ignite, gracefulShutdown } <span class="c-purple">from</span> <span class="c-green">'express-file-cluster'</span>;

<span class="c-blue">ignite</span>({
  cluster: <span class="c-orange">true</span>,
  tasks: { backend: <span class="c-green">'bullmq'</span> },
}).<span class="c-blue">then</span>(gracefulShutdown).<span class="c-blue">catch</span>(console.error);</pre>
`,
  },
  routing: {
    label: 'File-Based Routing',
    breadcrumb: 'Core / File-Based Routing',
    html: `
<h2>File-Based Routing</h2>
<p>EFC scans <code>src/api/</code> at startup and builds the route map from the file tree. No registration required — add a file, get a route.</p>
<h3>Routing Rules</h3>
<table class="docs-table">
  <thead><tr><th>File</th><th>URL</th></tr></thead>
  <tbody>
    <tr><td>src/api/health.ts</td><td>/health</td></tr>
    <tr><td>src/api/users/index.ts</td><td>/users</td></tr>
    <tr><td>src/api/users/[id].ts</td><td>/users/:id</td></tr>
    <tr><td>src/api/posts/[slug]/comments.ts</td><td>/posts/:slug/comments</td></tr>
  </tbody>
</table>
<h3>Method Dispatching</h3>
<p>Export uppercase HTTP method names. Unimplemented methods return <strong>405 Method Not Allowed</strong> automatically.</p>
<pre><span class="c-purple">export const</span> <span class="c-blue">GET</span>    = <span class="c-purple">async</span> (req, res) => { <span class="c-dim">/* ... */</span> };
<span class="c-purple">export const</span> <span class="c-blue">POST</span>   = <span class="c-purple">async</span> (req, res) => { <span class="c-dim">/* ... */</span> };
<span class="c-purple">export const</span> <span class="c-blue">PUT</span>    = <span class="c-purple">async</span> (req, res) => { <span class="c-dim">/* ... */</span> };
<span class="c-purple">export const</span> <span class="c-blue">PATCH</span>  = <span class="c-purple">async</span> (req, res) => { <span class="c-dim">/* ... */</span> };
<span class="c-purple">export const</span> <span class="c-blue">DELETE</span> = <span class="c-purple">async</span> (req, res) => { <span class="c-dim">/* ... */</span> };</pre>
<h3>Route metadata (<code>meta</code> export)</h3>
<p>Export a <code>meta</code> object to document the route in the development dashboard. All fields are optional.</p>
<pre><span class="c-purple">export const</span> meta = {
  description: <span class="c-green">'Fetch a user by ID.'</span>,
  request: {
    params: { id: <span class="c-green">'usr_01HXZ'</span> },
    query:  { include: <span class="c-green">'profile'</span> },
  },
  response: {
    status: <span class="c-orange">200</span>,
    body: { id: <span class="c-green">'usr_01HXZ'</span>, name: <span class="c-green">'Ada Lovelace'</span>, createdAt: <span class="c-green">'2026-01-01T00:00:00.000Z'</span> },
  },
};</pre>
<p>The dashboard renders <code>response.body</code> values as their type names — <code>String</code>, <code>Number</code>, <code>Boolean</code>, <code>Date</code>. ISO date strings are detected automatically and shown as <code>Date</code>.</p>
`,
  },
  handlers: {
    label: 'Route Handlers',
    breadcrumb: 'Core / Route Handlers',
    html: `
<h2>Route Handlers</h2>
<p>Handlers are standard Express <code>async (req, res) =&gt; {}</code> functions — no new patterns to learn.</p>
<h3>Static Route</h3>
<pre><span class="c-dim">// src/api/health.ts → GET /health</span>
<span class="c-purple">export const</span> <span class="c-blue">GET</span> = <span class="c-purple">async</span> (req, res) => {
  res.<span class="c-blue">json</span>({ status: <span class="c-green">'OK'</span>, ts: <span class="c-purple">new</span> Date().<span class="c-blue">toISOString</span>() });
};</pre>
<h3>Dynamic Route</h3>
<pre><span class="c-dim">// src/api/users/[id].ts → GET /users/:id</span>
<span class="c-purple">import</span> { HttpError } <span class="c-purple">from</span> <span class="c-green">'express-file-cluster'</span>;

<span class="c-purple">export const</span> <span class="c-blue">GET</span> = <span class="c-purple">async</span> (req, res) => {
  <span class="c-purple">const</span> user = <span class="c-purple">await</span> User.<span class="c-blue">findById</span>(req.params.id);
  <span class="c-purple">if</span> (!user) <span class="c-purple">throw new</span> <span class="c-blue">HttpError</span>(<span class="c-orange">404</span>, <span class="c-green">'User not found'</span>);
  res.<span class="c-blue">json</span>(user);
};</pre>
`,
  },
  middleware: {
    label: 'Middleware',
    breadcrumb: 'Core / Middleware',
    html: `
<h2>Middleware</h2>
<p>EFC supports three tiers of middleware with clear scopes.</p>
<h3>1. Global Middleware</h3>
<p>Set in <code>efc.config.ts</code> — applies before every route.</p>
<pre><span class="c-dim">// efc.config.ts</span>
<span class="c-purple">const</span> config: EFCConfig = {
  globalMiddlewares: [<span class="c-blue">cors</span>(), rateLimiter],
};</pre>
<h3>2. Route-Level Middleware</h3>
<pre><span class="c-dim">// Applied to all handlers in this file</span>
<span class="c-purple">export const</span> middlewares = [requireAuth, authorize(<span class="c-green">'admin'</span>)];

<span class="c-purple">export const</span> <span class="c-blue">DELETE</span> = <span class="c-purple">async</span> (req, res) => { <span class="c-dim">/* ... */</span> };</pre>
<h3>3. Handler-Level via <code>compose()</code></h3>
<pre><span class="c-purple">import</span> { compose } <span class="c-purple">from</span> <span class="c-green">'express-file-cluster'</span>;

<span class="c-purple">export const</span> <span class="c-blue">POST</span> = <span class="c-blue">compose</span>(
  <span class="c-blue">validateBody</span>(CreateUserSchema),
  <span class="c-purple">async</span> (req, res) => {
    <span class="c-dim">// req.body is validated here</span>
  }
);</pre>
`,
  },
  errors: {
    label: 'Error Handling',
    breadcrumb: 'Core / Error Handling',
    html: `
<h2>Error Handling</h2>
<p>Throw from any handler — EFC catches it and sends a clean JSON response.</p>
<h3>HttpError</h3>
<pre><span class="c-purple">import</span> { HttpError } <span class="c-purple">from</span> <span class="c-green">'express-file-cluster'</span>;

<span class="c-purple">export const</span> <span class="c-blue">GET</span> = <span class="c-purple">async</span> (req, res) => {
  <span class="c-purple">const</span> user = <span class="c-purple">await</span> User.<span class="c-blue">findById</span>(req.params.id);
  <span class="c-purple">if</span> (!user) <span class="c-purple">throw new</span> <span class="c-blue">HttpError</span>(<span class="c-orange">404</span>, <span class="c-green">'User not found'</span>);
  res.<span class="c-blue">json</span>(user);
};</pre>
<h3>Custom Global Handler</h3>
<pre><span class="c-blue">ignite</span>({
  <span class="c-blue">onError</span>: (err, req, res, next) => {
    logger.<span class="c-blue">error</span>(err);
    res.<span class="c-blue">status</span>(err.statusCode ?? <span class="c-orange">500</span>).<span class="c-blue">json</span>({ error: err.message });
  },
});</pre>
`,
  },
  clustering: {
    label: 'Clustering',
    breadcrumb: 'Features / Clustering',
    html: `
<h2>Clustering</h2>
<p>With <code>cluster: true</code>, EFC forks <code>os.cpus().length</code> workers. All share the same port — the OS round-robins connections across them.</p>
<h3>Pre-Flight Lifecycle (per worker)</h3>
<ul>
  <li>Connect database — establish this worker's pool</li>
  <li>Configure auth — wire JWT keys and cookie options</li>
  <li>Register tasks — scan <code>src/tasks/</code> and attach queue consumers</li>
  <li>Scan <code>src/api/</code> — build route map from the filesystem</li>
  <li>Mount routes — register handlers on Express</li>
  <li>Start listening — announce readiness</li>
</ul>
<h3>Self-Healing</h3>
<p>If a worker crashes, the master fires <code>onWorkerCrash</code>, immediately forks a replacement, and runs the full Pre-Flight lifecycle before serving traffic.</p>
<pre><span class="c-blue">ignite</span>({
  cluster: <span class="c-orange">true</span>,
  workers: <span class="c-orange">4</span>, <span class="c-dim">// default: os.cpus().length</span>
  <span class="c-blue">onWorkerReady</span>: (id) => console.<span class="c-blue">log</span>(<span class="c-green">\`Worker \${id} ready\`</span>),
  <span class="c-blue">onWorkerCrash</span>: (id, code) => console.<span class="c-blue">error</span>(<span class="c-green">\`Worker \${id} crashed (\${code})\`</span>),
});</pre>
`,
  },
  tasks: {
    label: 'Background Tasks',
    breadcrumb: 'Features / Background Tasks',
    html: `
<h2>Background Tasks</h2>
<p>Define tasks in <code>src/tasks/</code>. Enqueue from any route handler. Respond immediately — the job runs later.</p>
<h3>Defining an I/O-bound task</h3>
<pre><span class="c-purple">import</span> { defineTask } <span class="c-purple">from</span> <span class="c-green">'express-file-cluster/tasks'</span>;

<span class="c-purple">export default</span> <span class="c-blue">defineTask</span>&lt;{ to: string; subject: string }&gt;(
  <span class="c-purple">async</span> (payload) => { <span class="c-purple">await</span> mailer.<span class="c-blue">send</span>(payload); }
);</pre>
<h3>CPU-bound task (worker_threads)</h3>
<pre><span class="c-purple">export default</span> <span class="c-blue">defineTask</span>&lt;{ key: string; width: number }&gt;(
  { thread: <span class="c-orange">true</span> },
  <span class="c-purple">async</span> ({ key, width }) => {
    <span class="c-purple">const</span> out = <span class="c-purple">await</span> sharp(<span class="c-purple">await</span> <span class="c-blue">download</span>(key)).<span class="c-blue">resize</span>(width).<span class="c-blue">toBuffer</span>();
    <span class="c-purple">await</span> <span class="c-blue">upload</span>(\`\${key}@\${width}\`, out);
  }
);</pre>
<h3>Task Options</h3>
<table class="docs-table">
  <thead><tr><th>Option</th><th>Default</th><th>Description</th></tr></thead>
  <tbody>
    <tr><td>thread</td><td>false</td><td>Run in worker_threads</td></tr>
    <tr><td>retries</td><td>3</td><td>Retry attempts before dead-letter</td></tr>
    <tr><td>backoff</td><td>'exponential'</td><td>Delay strategy between retries</td></tr>
    <tr><td>concurrency</td><td>tasks.concurrency</td><td>Parallel jobs for this task</td></tr>
    <tr><td>schedule</td><td>—</td><td>Cron expression for recurring tasks (planned, not yet executed)</td></tr>
  </tbody>
</table>
`,
  },
  auth: {
    label: 'Authentication',
    breadcrumb: 'Features / Authentication',
    html: `
<h2>Authentication</h2>
<p>Choose your strategy during scaffolding. Both ship JWT-based token management.</p>
<h3>http-only (recommended for SSR)</h3>
<p>Tokens stored in <strong>HttpOnly + Secure + SameSite=Strict</strong> cookies.</p>
<pre><span class="c-purple">import</span> { issueToken, revokeToken, requireAuth }
  <span class="c-purple">from</span> <span class="c-green">'express-file-cluster/auth'</span>;

<span class="c-dim">// Login route</span>
<span class="c-purple">export const</span> <span class="c-blue">POST</span> = <span class="c-purple">async</span> (req, res) => {
  <span class="c-purple">const</span> user = <span class="c-purple">await</span> <span class="c-blue">verifyCredentials</span>(req.body);
  <span class="c-purple">await</span> <span class="c-blue">issueToken</span>(res, { sub: user.id, role: user.role });
  res.<span class="c-blue">json</span>({ message: <span class="c-green">'Logged in'</span> });
};

<span class="c-dim">// Protect a route</span>
<span class="c-purple">export const</span> middlewares = [requireAuth];</pre>
<h3>localStorage (SPA-friendly)</h3>
<pre><span class="c-purple">import</span> { signToken } <span class="c-purple">from</span> <span class="c-green">'express-file-cluster/auth'</span>;

<span class="c-purple">export const</span> <span class="c-blue">POST</span> = <span class="c-purple">async</span> (req, res) => {
  <span class="c-purple">const</span> token = <span class="c-purple">await</span> <span class="c-blue">signToken</span>({ sub: user.id });
  res.<span class="c-blue">json</span>({ token }); <span class="c-dim">// client: Authorization: Bearer &lt;token&gt;</span>
};</pre>
`,
  },
  rbac: {
    label: 'RBAC',
    breadcrumb: 'Features / RBAC',
    html: `
<h2>Role-Based Access Control</h2>
<p>Role checks are built into <code>requireAuth</code> itself — call it with role names instead of reaching for a separate middleware. Toggle <strong>Role-based access control</strong> in the scaffolder to also generate a <code>Role</code> model and switch every protected route to this shorthand.</p>
<h3><code>requireAuth(...roles)</code></h3>
<pre><span class="c-purple">import</span> { requireAuth } <span class="c-purple">from</span> <span class="c-green">'express-file-cluster/auth'</span>;

<span class="c-dim">// bare — auth only</span>
<span class="c-purple">export const</span> middlewares = [requireAuth];

<span class="c-dim">// auth + role check — 403 if payload.role isn't one of these</span>
<span class="c-purple">export const</span> middlewares = [<span class="c-blue">requireAuth</span>(<span class="c-green">'admin'</span>)];
<span class="c-purple">export const</span> middlewares = [<span class="c-blue">requireAuth</span>(<span class="c-green">'user'</span>, <span class="c-green">'admin'</span>)];</pre>
<h3>Applied automatically</h3>
<p>Every protected route the scaffolder generates switches from an inline <code>user.role === 'admin'</code> guard to:</p>
<pre><span class="c-purple">export const</span> middlewares = [<span class="c-blue">requireAuth</span>(<span class="c-green">'admin'</span>)];</pre>
<p>Also generates a <code>Role</code> model, and — if <strong>Admin portal</strong> is also enabled — a full <code>/admin/roles</code> CRUD API.</p>
`,
  },
  database: {
    label: 'Database',
    breadcrumb: 'Features / Database',
    html: `
<h2>Database</h2>
<p>One unified model surface designed to compile to Mongoose or Drizzle depending on your config. <strong>Only the MongoDB adapter is implemented today</strong> — PostgreSQL is a selectable choice in the scaffolder but only produces commented-out schema stubs until the Drizzle adapter lands in Phase 2.</p>
<h3>defineModel — engine-agnostic CRUD</h3>
<pre><span class="c-purple">import</span> { defineModel } <span class="c-purple">from</span> <span class="c-green">'express-file-cluster'</span>;

<span class="c-purple">export const</span> User = <span class="c-blue">defineModel</span>(<span class="c-green">'User'</span>, {
  name:  { type: <span class="c-green">'string'</span>, required: <span class="c-orange">true</span> },
  email: { type: <span class="c-green">'string'</span>, required: <span class="c-orange">true</span>, unique: <span class="c-orange">true</span> },
  role:  { type: <span class="c-green">'string'</span>, default: <span class="c-green">'member'</span> },
});</pre>
<h3>Available Methods</h3>
<table class="docs-table">
  <thead><tr><th>Method</th><th>Returns</th></tr></thead>
  <tbody>
    <tr><td>Model.find(filter?)</td><td>Record[]</td></tr>
    <tr><td>Model.findById(id)</td><td>Record | null</td></tr>
    <tr><td>Model.findOne(filter)</td><td>Record | null</td></tr>
    <tr><td>Model.create(data)</td><td>Record</td></tr>
    <tr><td>Model.update(id, data)</td><td>Record | null</td></tr>
    <tr><td>Model.delete(id)</td><td>void</td></tr>
    <tr><td>Model.count(filter?)</td><td>number</td></tr>
  </tbody>
</table>
<h3>Raw Client (escape hatch)</h3>
<pre><span class="c-purple">import</span> { db } <span class="c-purple">from</span> <span class="c-green">'express-file-cluster'</span>;
<span class="c-dim">// MongoDB: db is a mongoose.Connection</span>
<span class="c-dim">// PostgreSQL: db is a pg.Pool</span>
<span class="c-purple">const</span> { rows } = <span class="c-purple">await</span> db.<span class="c-blue">query</span>(<span class="c-green">'SELECT * FROM users WHERE id = $1'</span>, [id]);</pre>
`,
  },
  mailer: {
    label: 'Mailer',
    breadcrumb: 'Features / Mailer',
    html: `
<h2>Mailer</h2>
<p>Toggle <strong>Mailer</strong> during scaffolding to get a working <code>nodemailer</code> transport wired to environment variables, plus a real <code>SendEmail</code> task — no hand-written SMTP boilerplate.</p>
<h3>Choose a provider</h3>
<pre><span class="c-dim">? Email provider:
  ❯ Gmail                 smtp.gmail.com, preconfigured
    Other (custom SMTP)   you'll provide host + port</span></pre>
<p>Pick <strong>Gmail</strong> and no host/port question is asked at all — <code>SMTP_HOST</code>/<code>SMTP_PORT</code> are set to <code>smtp.gmail.com</code> / <code>465</code> automatically. Pick <strong>Other</strong> and you're prompted for both.</p>
<h3>Gmail requires an App Password</h3>
<p>Google rejects your normal account password for SMTP. The wizard shows a note and then validates the password is exactly <strong>16 characters</strong> (Gmail App Password length) before accepting it:</p>
<blockquote>Generate a 16-character App Password: Google Account → Security → 2-Step Verification → App passwords. Enter it below without spaces.</blockquote>
<h3>Generated task</h3>
<pre><span class="c-purple">import</span> { defineTask } <span class="c-purple">from</span> <span class="c-green">'express-file-cluster/tasks'</span>;
<span class="c-purple">import</span> nodemailer <span class="c-purple">from</span> <span class="c-green">'nodemailer'</span>;

<span class="c-purple">const</span> transporter = nodemailer.<span class="c-blue">createTransport</span>({
  host: process.env.SMTP_HOST,
  port: <span class="c-blue">Number</span>(process.env.SMTP_PORT ?? <span class="c-orange">587</span>),
  secure: <span class="c-blue">Number</span>(process.env.SMTP_PORT) === <span class="c-orange">465</span>,
  auth: { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS },
});

<span class="c-purple">export default</span> <span class="c-blue">defineTask</span>(<span class="c-purple">async</span> (payload) => {
  <span class="c-purple">await</span> transporter.<span class="c-blue">sendMail</span>({
    from: process.env.SMTP_FROM ?? process.env.SMTP_USER,
    to: payload.to,
    subject: payload.subject,
    html: payload.body,
  });
});</pre>
<p>Trigger it with <code>enqueue('SendEmail', payload)</code> from any route — see <a href="#" onclick="document.querySelector('[data-doc=tasks]').click()">Background Tasks</a>.</p>
<h3>Wired into the auth flow automatically</h3>
<p>With <strong>User portal</strong> + <strong>Mailer</strong> both on (MongoDB), <code>register</code>, <code>forgot-password</code>, and the <code>verify-email</code> resend endpoint call <code>enqueue('SendEmail', ...)</code> for you — no wiring required. Without Mailer, they still generate and store the token, just with a <code>// TODO</code> where the email send would go.</p>
`,
  },
  dashboard: {
    label: 'API Dashboard',
    breadcrumb: 'Features / API Dashboard',
    html: `
<h2>API Dashboard</h2>
<p>EFC automatically mounts a live API documentation page at <code>GET /</code> when <code>NODE_ENV === 'development'</code>. It lists every registered route with its method, path, description, and request/response examples — no external tooling required.</p>
<h3>Enabling it</h3>
<p>The dashboard is <strong>on by default in development</strong> — no config needed. In production (<code>NODE_ENV=production</code>) the route does not exist.</p>
<h3>Documenting routes with <code>meta</code></h3>
<p>Export a <code>meta</code> object from any route file to populate the dashboard card for that route.</p>
<pre><span class="c-dim">// src/api/users/[id].ts</span>
<span class="c-purple">export const</span> meta = {
  description: <span class="c-green">'Fetch a user by ID.'</span>,
  request: {
    headers: { Authorization: <span class="c-green">'Bearer &lt;token&gt;'</span> },
    params:  { id: <span class="c-green">'usr_01HXZ'</span> },
    query:   { include: <span class="c-green">'profile'</span> },
  },
  response: {
    status: <span class="c-orange">200</span>,
    body: {
      id:        <span class="c-green">'usr_01HXZ'</span>,
      name:      <span class="c-green">'Ada Lovelace'</span>,
      createdAt: <span class="c-green">'2026-01-01T00:00:00.000Z'</span>,
    },
  },
};</pre>
<h3>Type rendering</h3>
<p>The dashboard renders <code>response.body</code> values as their <strong>type names</strong>, not the literal values you provide. This keeps examples readable without leaking real data.</p>
<table class="docs-table">
  <thead><tr><th>Value in meta</th><th>Shown in dashboard</th></tr></thead>
  <tbody>
    <tr><td>'Ada Lovelace'</td><td>String</td></tr>
    <tr><td>42891</td><td>Number</td></tr>
    <tr><td>true / false</td><td>Boolean</td></tr>
    <tr><td>'2026-01-01T00:00:00.000Z'</td><td>Date</td></tr>
  </tbody>
</table>
<p>ISO 8601 date strings are detected automatically — no annotation needed.</p>
<h3>RouteMeta interface</h3>
<pre><span class="c-purple">interface</span> <span class="c-blue">RouteMeta</span> {
  description?: string;
  request?: {
    headers?: Record&lt;string, string&gt;;
    params?:  Record&lt;string, string&gt;;
    query?:   Record&lt;string, string&gt;;
    body?:    unknown;
  };
  response?: {
    status?: number;
    body?:   unknown;
  };
}</pre>
`,
  },
  portals: {
    label: 'Generated Portals',
    breadcrumb: 'Scaffolding / Generated Portals',
    html: `
<h2>Generated Portals</h2>
<p>The <strong>User portal</strong> and <strong>Admin portal</strong> feature options scaffold a large, ready-to-run set of models and routes — not stubs. On MongoDB every model is a real <code>defineModel</code> collection with working CRUD; on PostgreSQL they're commented-out Drizzle stubs until that adapter ships.</p>
<h3>User portal — models</h3>
<p><code>User</code>, <code>Session</code>, <code>Notification</code>, <code>File</code>, <code>SupportTicket</code>, <code>Subscription</code>, <code>Invoice</code>, <code>ApiKey</code></p>
<h3>User portal — routes (40+)</h3>
<p>Auth extras (<code>register</code>, <code>me</code>, <code>refresh</code>, email verification, password reset/change, 2FA setup/verify/disable, session listing), profile + avatar + settings + account deletion, notifications CRUD, file uploads, favorites/bookmarks, search, API keys, billing (plans, subscription, payment methods, invoices), and support tickets.</p>
<h3>Admin portal — models</h3>
<p><code>Admin</code>, <code>SupportTicket</code>, <code>AuditLog</code>, <code>Plan</code>, <code>FAQ</code>, <code>Blog</code>, <code>Category</code>, <code>Coupon</code></p>
<h3>Admin portal — routes (35+)</h3>
<p>Dashboard stats, user management (suspend/activate/verify/export CSV), analytics, admin management, notification broadcast, audit/activity/security logs, system health, support ticket triage, content management (FAQs, blog, categories), billing (plans, coupons, subscriptions) — plus a full <code>/admin/roles</code> CRUD API if <a href="#" onclick="document.querySelector('[data-doc=rbac]').click()">RBAC</a> is also enabled.</p>
<p>Every protected route exports <code>middlewares = [requireAuth]</code>, or <code>[requireAuth('admin')]</code> if RBAC is on.</p>
`,
  },
  cli: {
    label: 'CLI Reference',
    breadcrumb: 'Reference / CLI',
    html: `
<h2>CLI Reference</h2>
<h3>Lifecycle</h3>
<table class="docs-table">
  <thead><tr><th>Command</th><th>Description</th></tr></thead>
  <tbody>
    <tr><td>efc start dev</td><td>Dev server — hot-reload, single process. <code>NODE_ENV</code> defaults to <code>development</code>; overridden by <code>.env</code> or parent environment</td></tr>
    <tr><td>efc build prod</td><td>Type-check + compile to dist/ (tsup, dual CJS/ESM)</td></tr>
    <tr><td>efc start prod</td><td>Run dist/ with clustering enabled</td></tr>
    <tr><td>efc run tests</td><td>Vitest — pass --watch or --coverage</td></tr>
  </tbody>
</table>
<h3>Code Generation</h3>
<table class="docs-table">
  <thead><tr><th>Command</th><th>Description</th></tr></thead>
  <tbody>
    <tr><td>efc generate route users/[id]</td><td>Scaffold a route module with method stubs</td></tr>
    <tr><td>efc generate task SendEmail</td><td>Scaffold a background task</td></tr>
    <tr><td>efc generate middleware authorize</td><td>Scaffold a middleware file</td></tr>
  </tbody>
</table>
<h3>Diagnostics</h3>
<table class="docs-table">
  <thead><tr><th>Command</th><th>Description</th></tr></thead>
  <tbody>
    <tr><td>efc routes</td><td>Print resolved route table (path → file → methods)</td></tr>
    <tr><td>efc tasks</td><td>List registered background tasks</td></tr>
    <tr><td>efc doctor</td><td>Validate config, env vars, DB connectivity</td></tr>
  </tbody>
</table>
`,
  },
  envvars: {
    label: 'Environment Variables',
    breadcrumb: 'Reference / Environment Variables',
    html: `
<h2>Environment Variables</h2>
<p><code>create-efc-app</code> generates a <code>.env</code> (gitignored, JWT_SECRET pre-filled) and <code>.env.example</code> (committed, documented placeholders).</p>
<table class="docs-table">
  <thead><tr><th>Variable</th><th>Required</th><th>Description</th></tr></thead>
  <tbody>
    <tr><td>PORT</td><td>No (3000)</td><td>HTTP listen port</td></tr>
    <tr><td>NODE_ENV</td><td>No</td><td>development | production | test</td></tr>
    <tr><td>DATABASE_URL</td><td>Yes</td><td>MongoDB or PostgreSQL connection string</td></tr>
    <tr><td>JWT_SECRET</td><td>Yes</td><td>JWT signing key — auto-generated by scaffolder</td></tr>
    <tr><td>JWT_EXPIRES_IN</td><td>No (7d)</td><td>Token lifetime: 15m, 1h, 7d …</td></tr>
    <tr><td>COOKIE_DOMAIN</td><td>No</td><td>Cookie domain for http-only auth</td></tr>
    <tr><td>REDIS_URL</td><td>If BullMQ</td><td>Redis connection for task queue</td></tr>
    <tr><td>CORS_ORIGINS</td><td>No</td><td>Comma-separated allowed origins (e.g. <code>http://localhost:3000,https://yourapp.com</code>)</td></tr>
    <tr><td>SMTP_HOST</td><td>If Mailer</td><td>smtp.gmail.com, or your custom SMTP host</td></tr>
    <tr><td>SMTP_PORT</td><td>If Mailer</td><td>465 (Gmail) or 587 (custom, typical)</td></tr>
    <tr><td>SMTP_USER</td><td>If Mailer</td><td>Sending email address</td></tr>
    <tr><td>SMTP_PASS</td><td>If Mailer</td><td>For Gmail: a 16-character App Password — <strong>not</strong> your Gmail login password</td></tr>
    <tr><td>SMTP_FROM</td><td>If Mailer</td><td>From: address on outgoing mail — defaults to SMTP_USER</td></tr>
  </tbody>
</table>
`,
  },
};

/* ─── DOCS RENDERING ─── */
function renderAllDocs() {
  const contentEl = document.getElementById('docsContent');
  contentEl.innerHTML = '';
  
  for (const [key, doc] of Object.entries(DOCS)) {
    const wrappedHtml = doc.html.replace(/<table/g, '<div class="table-responsive"><table').replace(/<\/table>/g, '</table></div>');
    const sectionHtml = `
      <div id="doc-${key}" class="doc-section">
        ${wrappedHtml}
      </div>
    `;
    contentEl.insertAdjacentHTML('beforeend', sectionHtml);
  }
}

renderAllDocs();

/* ─── DOCS SCROLLSPY & NAVIGATION ─── */
const docsObserver = new IntersectionObserver((entries) => {
  entries.forEach((entry) => {
    if (entry.isIntersecting) {
      const key = entry.target.id.replace('doc-', '');
      document.querySelectorAll('.docs-nav-link').forEach((l) => {
        l.classList.toggle('active', l.dataset.doc === key);
      });
    }
  });
}, { rootMargin: '-100px 0px -60% 0px' });

document.querySelectorAll('.doc-section').forEach((sec) => docsObserver.observe(sec));

document.querySelectorAll('.docs-nav-link').forEach((link) => {
  link.addEventListener('click', (e) => {
    e.preventDefault();
    const key = link.dataset.doc;
    const target = document.getElementById('doc-' + key);
    if (target) {
      target.scrollIntoView({ behavior: 'smooth' });
    }
  });
});

/* ─── TABS ─── */
document.querySelectorAll('.tab').forEach((tab) => {
  tab.addEventListener('click', () => {
    document.querySelectorAll('.tab').forEach((t) => t.classList.remove('active'));
    document.querySelectorAll('.tab-pane').forEach((p) => p.classList.remove('active'));
    tab.classList.add('active');
    document.getElementById('tab-' + tab.dataset.tab).classList.add('active');
  });
});

/* ─── NAVBAR SCROLL ─── */
window.addEventListener('scroll', () => {
  document.getElementById('navbar').classList.toggle('scrolled', window.scrollY > 20);
});

/* ─── HAMBURGER ─── */
document.getElementById('hamburger').addEventListener('click', () => {
  document.getElementById('mobileMenu').classList.toggle('open');
});

/* ─── INTERSECTION OBSERVER — fade in on scroll ─── */
const observer = new IntersectionObserver(
  (entries) => {
    entries.forEach((entry) => {
      if (entry.isIntersecting) {
        entry.target.style.opacity = '1';
        entry.target.style.transform = 'translateY(0)';
      }
    });
  },
  { threshold: 0.1 },
);

document.querySelectorAll('.feature-card, .roadmap-phase, .cta-inner').forEach((el) => {
  el.style.opacity = '0';
  el.style.transform = 'translateY(20px)';
  el.style.transition = 'opacity .5s ease, transform .5s ease';
  observer.observe(el);
});
