import { Command } from 'commander';
import { spawn } from 'node:child_process';
import path from 'node:path';
import fs from 'node:fs';
import pc from 'picocolors';

export function startCommand(): Command {
  const cmd = new Command('start');

  cmd
    .argument('<mode>', 'dev | prod')
    .description('Start the EFC server')
    .action((mode: string) => {
      if (mode === 'dev') {
        startDev();
      } else if (mode === 'prod') {
        startProd();
      } else {
        console.error(pc.red(`Unknown mode: ${mode}. Use 'dev' or 'prod'.`));
        process.exit(1);
      }
    });

  return cmd;
}

// tsx watch restarts the entry module in place rather than spawning a brand-new OS process
// per change, so process.env itself persists (with its mutations) across restarts. A preload
// that re-reads .env on every restart therefore can't just do "only set if currently unset" —
// by the second restart, every key it set last time already looks "currently set" and a
// naive check would treat a prior injection the same as a real OS-exported var, freezing
// stale values forever. Instead it tracks which keys IT injected (via a marker env var) so
// its own previous writes are always safe to overwrite, while true external env vars — never
// present in that marker — still win, same as before.
function writeDevEnvPreload(cwd: string): string {
  const cacheDir = path.join(cwd, 'node_modules', '.cache', 'efc');
  fs.mkdirSync(cacheDir, { recursive: true });
  const preloadPath = path.join(cacheDir, 'dev-env-preload.mjs');
  const source = `// Auto-generated by \`efc start dev\` — re-reads .env fresh on every restart
// so tsx watch restarts always pick up the latest .env, instead of reusing a stale snapshot.
import fs from 'node:fs';
import path from 'node:path';

const MARKER = '__EFC_DOTENV_KEYS__';
const previouslyInjected = new Set((process.env[MARKER] ?? '').split(',').filter(Boolean));
const injectedNow = [];

const envFile = path.join(process.cwd(), '.env');
if (fs.existsSync(envFile)) {
  for (const line of fs.readFileSync(envFile, 'utf8').split('\\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const raw = trimmed.slice(eq + 1).trim();
    // A key we injected on a previous restart is always safe to refresh; a key we've never
    // injected and that's already set is a real external env var, which still wins.
    if (previouslyInjected.has(key) || process.env[key] === undefined) {
      process.env[key] = raw.replace(/^(['"])(.*)\\1$/, '$2');
      injectedNow.push(key);
    }
  }
}
process.env[MARKER] = injectedNow.join(',');
`;
  fs.writeFileSync(preloadPath, source);
  return preloadPath;
}

function startDev(): void {
  const entry = resolveEntry();
  if (!entry) {
    console.error(pc.red('[EFC] Could not find entry point. Expected src/index.ts or index.ts'));
    process.exit(1);
  }

  console.log(pc.cyan('[EFC] Starting development server…'));
  console.log(pc.dim(`  Entry: ${entry}`));
  console.log(pc.dim('  .env is re-read fresh on every restart (no need to stop/restart `efc start dev` for .env changes to take effect)'));

  const cwd = process.cwd();
  // Walk up from cwd looking for tsx in node_modules/.bin (handles workspace hoisting)
  function findTsx(): string {
    let dir = cwd;
    while (true) {
      const candidate = path.join(dir, 'node_modules', '.bin', 'tsx');
      if (fs.existsSync(candidate)) return candidate;
      const parent = path.dirname(dir);
      if (parent === dir) return 'tsx'; // reached filesystem root, fall back to PATH
      dir = parent;
    }
  }
  const tsx = findTsx();
  const preloadPath = writeDevEnvPreload(cwd);

  const env: NodeJS.ProcessEnv = {
    NODE_ENV: 'development',
    ...process.env,
    NODE_OPTIONS: [process.env['NODE_OPTIONS'], `--import ${preloadPath}`]
      .filter(Boolean)
      .join(' '),
  };

  const child = spawn(tsx, ['watch', '--include', 'src', entry], { stdio: 'inherit', env });
  child.on('exit', (code) => process.exit(code ?? 0));
}

function startProd(): void {
  const cwd = process.cwd();
  const distEntry = path.join(cwd, 'dist', 'index.js');

  if (!fs.existsSync(distEntry)) {
    console.error(pc.red('[EFC] dist/index.js not found. Run `efc build prod` first.'));
    process.exit(1);
  }

  console.log(pc.cyan('[EFC] Starting production server…'));

  // Production env comes exclusively from process.env — no .env file loading.
  // Platforms (Docker, Kubernetes, Railway, Heroku, etc.) inject vars directly.
  const child = spawn('node', [distEntry], {
    stdio: 'inherit',
    env: { ...process.env, NODE_ENV: 'production' },
  });
  child.on('exit', (code) => process.exit(code ?? 0));
}

function resolveEntry(): string | null {
  const cwd = process.cwd();
  const candidates = [
    path.join(cwd, 'src', 'index.ts'),
    path.join(cwd, 'index.ts'),
    path.join(cwd, 'src', 'index.js'),
    path.join(cwd, 'index.js'),
  ];
  return candidates.find((f) => fs.existsSync(f)) ?? null;
}
